repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.29.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.29.0
          - eslint-config-standard-with-typescript@23.0.0
          - eslint-plugin-import@2.26.0
          - "@typescript-eslint/eslint-plugin@5.46.1"
